spring.application.name=product-service
server.port=8080

# MongoDB
# Từ Spring Boot 3.x trở lên, các thuộc tính host, port, database đã bị loại bỏ hoàn toàn.
# Phải sử dụng URI để cấu hình kết nối, nếu không Spring Boot sẽ tự động kết nối vào database mặc định là 'test'
spring.data.mongodb.uri=mongodb://root:password@localhost:27017/product-service?authSource=admin